### ISSUE TITLE
appsettings settings result in malformed url for ConfigServer

### ISSUE THREAD

**Issue by stan-exostar** [SteeltoeOSS/Steeltoe#1045]
## Describe the bug
The schema https://steeltoe.io/schema/latest/schema.json doesn't match the documentation, as it has "Environment" instead of "Env" under Spring:Cloud:Config, but that's not the bug.  

The Url that Steeltoe uses to reach Spring Config Server isn't formed correcty based on the proper use of Spring:Cloud:Config:Name (supposed to be Profile name) and Spring:Application:Name (which appears to be ignored). Instead, in the place in the Url where Spring:Cloud:Config:Name should be used, Spring:Cloud:Config:Env is used. In the place where Spring:Application:Name should be used, Spring:Cloud:Config:Name is used.

## Steps to reproduce 
1. Configure Spring:Application:Name with application name
2. Configure Spring:Cloud:Config:Name with Profile name(s) - try two, comma delimited
3. Enable logging (builder.Configuration.AddConfigServer(loggerFactory);)
4. Configure logging ("Steeltoe.Configuration.ConfigServer": "Debug")
5. Build and run your app from command line (dotnet run projectname.csproj)
6. You will get no entries from config server.
7. Examine console log and look at info: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider[0] Config Server returned status OK invoking path [path]

The path (once you decode it) is incorrect. It was:
s:c:c: Url :  http://localhost:9098/myapi/v1/config
then "/" + the last of the comma separated profile names (from s:c:c:Name)
then "/" + the environment name (from s:c:c:Env)
then "/" + the label (from s:c:c:Label), which in my case is the git repo branch and was correct

This resulted in the url (note that it had only one profile, not in the right place, followed by the s:c:c:Env setting):
http://localhost:9098/myapi/v1/config/DEV/Dev/develop

## Expected behavior
The url should have used the Spring:Application:Name and the Spring:Cloud:Config:Name (profile) to build the url, as in:

s:c:s:Uri :  http://localhost:9098/myapi/v1/config
then "/" + the application name (from Spring:Application:Name)
then "/" + the comma separated profile names (from s:c:c:Name) in entirety
then "/" + the label (from s:c:c:Label), which in my case is the git repo branch

This would be (note that I have two profiles to return entries for):
http://localhost:9098/myapi/v1/config/PoC/Stan_DEV,DEV/develop

Note that if I browse to this url, it returns all configuration settings, so it is indeed correct.

## Environment (please complete the following information):
 - Steeltoe Version 3.2.2 (was 3.2.1, but logging wasn't working)
 - Platform: Spring Cloud Config
 - OS: Windows 11
 - .NET Version: .NET 6

**Comment by stan-exostar** [comment]
While this is just an example repo for the config server itself, the readme shows a table of resources showing the url (after base url) that might help.

https://github.com/spring-cloud-samples/configserver

**Comment by dtillman** [comment]
Hi @stan-exostar,
Here is the Steeltoe and Spring documentation relevant to the discussion that follows: 

Steeltoe: https://docs.steeltoe.io/api/v3/configuration/config-server-provider.html#configure-settings
Spring: https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_spring_cloud_config_client

First, you will find that not all settings available for the Java Spring Config Server client are available for the Steeltoe client and also not all settings names match exactly.  They are close ... but not exactly the same.

Second, spring:cloud:config:name is the configured name of the application, as it pertains to the config server client ... not the profile name.  I'm pretty sure that is true for Spring java client as well .. but haven't looked closely in a while.

Third, spring:application:name can also be used as the configured name of the application.  It is a global setting that can be used by all of our Steeltoe packages(i.e. config server, discovery, etc.) when an application name is needed by the library code. Each library can enable that setting to be override using a different key specific to that library... like in the case of config server client you can use spring:cloud:config:name.  

If the above is not working for you ... let me know ... it's probably a bug.

Last, Steeltoe does not have the concept of a "profile" in the same way that Spring has.   So we decided years ago when we developed the Steeltoe Config Server client that we would map the closest thing we could find in .NET to a Spring "profile"... and that was the .NET "Environment" name setting (i.e. "Debug", etc.).  As it relates to usage within the Steeltoe config server client, the .NET environment name (IHostingEnvironment.EnvironmentName) is used, by default, as the "profile".  If you don't want the default name, as provided by .NET, you can configure it using the Steeltoe spring:cloud:config:env setting.   

Ya, we picked "env" instead of "profile" as the config key... and in hindsight... it might have been better to have just used "spring:cloud:config:profile". ;-)

I hope I've addressed all your issues... 

Dave

**Comment by stan-exostar** [comment]
Okay, I can see where some things had to be done to fit like you mentioned. But you said "Second, spring:config:name is the configured name of the application, as it pertains to the config server client..." and "spring:application:name can also be used as the configured name of the application", and this is something I actually expected when I wrote that the correct format for the service call to get the configuration would have been this:

s:c:s:Uri : http://localhost:9098/myapi/v1/config
**then "/" + the application name (from Spring:Application:Name)**
then "/" + the comma separated profile names (from s:c:c:Name) in entirety
then "/" + the label (from s:c:c:Label), which in my case is the git repo branch

But you're using Spring:Cloud:Config:Name instead of Spring:Application:Name here.  Or is that not what you meant?

Mapping the Env rather than Spring:Cloud:Config:Name (profile) is no biggie, but should be in the documentation so developers know that this is where the profile name(s) would go, maybe?

**Comment by dtillman** [comment]
@stan-exostar 
Here is some specifics from the Spring Config Client documentation that is relevant describing the request and what the Java Spring client uses for each element by default and how you can configure it:
https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_locating_remote_configuration_resources

Yes, spring:cloud:config:name should override spring:application:name  when used to fetch the configuration from the config server.   (i.e. the "application" part of the "/{application}/{profile}/{label}" If you don't specify s:c:c:name, then s:a:n should be used.  If you don't configure either, then IHostingEnvironment.ApplicationName should be used.

The "profile" comes from (IHostingEnvironment.EnvironmentName) by default, or in Steeltoe you can configure the value using spring:cloud:config:env (i.e. the "profile" part of the "/{application}/{profile}/{label}"

The label defaults to "master" I think... maybe we changed it to "main", anyway with Steeltoe you can configure it using spring:cloud:config:label  (i.e. the "label" part of the "/{application}/{profile}/{label}"

Let me know if you are not seeing this kind of behavior.

**Comment by dtillman** [comment]
Closing due to no additional feedback ..
