### ISSUE TITLE
Native Kubernetes Service discovery

### ISSUE THREAD

**Issue by mohanr** [SteeltoeOSS/Steeltoe#107]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
I see that the supported Service discovery mechanisms need either Eureka or Consul. But I am looking for discovery using Native Kubernetes API.

**Comment by tscrypter** [comment]
I'd like to pick this issue up and submit a PR. I wanted to reach out first to ensure someone else wasn't already planning on doing this work and to solicit any thoughts/opinions others may have on a potential solution. I was going to follow any patterns already in place with the Eureka/Consul discovery clients and mirror my k8s implementation to something similar in the Spring-Cloud-Kubernetes discovery client.

**Comment by tscrypter** [comment]
When you mention taking a dependency on `KubernetesClient`, what kind of functionality are you expecting that client to have? Is it enough if the `KubernetesClient` has a property for a `KubernetesSettingsReader` on it? I was going to create a class similar to `CloudFoundryEnvironmentSettingsReader` for extracting the service routes injected into the container's environment vars to support the service discovery.

**Comment by TimHess** [comment]
I was referring to the [KubernetesClient NuGet Package](https://www.nuget.org/packages/KubernetesClient). My expectation was that we'd be able to interact with the kubernetes api in order to retrieve things like configmaps and secrets directly. It might be useful for active lookups on services, but I hadn't begun to dig in there.

Using the environment variables could be viable, that is one idea I had in the back of my mind... I don't know yet what the best answer is so I'm open to what you find. For what it's worth, there is already a (clearly not compatible with Kubernetes) configuration-based config provider in [here](https://github.com/SteeltoeOSS/steeltoe/tree/master/src/Common/src/Common/Discovery), I think it's probably only used for some of our unit tests. Relying on the environment variables would be simpler than using the API for sure, but I don't know yet how well that approach deals with real-time changes to which services are available.

I'm not planning on working over the weekend, so I pushed up the (very, very preliminary) work I have done so far to [this branch](https://github.com/SteeltoeOSS/steeltoe/tree/k8s) if that's of any use to you.

As an aside, you can also reach me on the Steeltoe Slack

**Comment by tscrypter** [comment]
Awesome, thank you very much. I joined the slack channel, so I'll probably post a few updates and questions I may have in the process.
Now that you mention it, making use of the k8s api may be a more reliable approach. Using environment variables adds the additional dependency that the pods are created after the services for the environment variables to be injected that could possibly be avoided if the same information is available via the API.

**Comment by TimHess** [comment]
Hey @tscrypter, you still going strong on this? Not intending to rush you or anything, just checking if you need anything!

Adding a link to your branch for tracking... https://github.com/SteeltoeOSS/Steeltoe/compare/master...tscrypter:tscrypter/107/k8s-native-service-discovery

**Comment by tscrypter** [comment]
Hey @TimHess ,
I'm still making progress on this. I got some scaffolding in place and am working on adding automated tests while ironing out the wrinkles currently.
