### ISSUE TITLE
SqlServer IHealthContributor injected when no connection is specified

### ISSUE THREAD

**Issue by davgia** [SteeltoeOSS/Steeltoe#1126]
## Describe the bug
The SqlServer IHealthContributor is injected when no sqlserver connection is specified in the configuration. The default `localhost:1433` is used and causes the health actuator to report "DOWN".

## Steps to reproduce 
1. Create a basic .net 6 microservice
2. Add Steeltoe dependencies (ConnectorCore, EndpointCore, Autoconfig) - 3.2.3
3. Add Microsoft.Data.SqlClient dependency - 5.1.1

## Expected behavior
If no configuration values under `SqlServer:Credentials` are specified the IHealthContributor for SqlServer should not be configured.
My current fix is the following:

``` cs
public static IHostBuilder CreateHostBuilder(string[] args, bool isService = false)
{
    var builder = Host.CreateDefaultBuilder(args);

    //FIX: exclude connectorCore from autoconfig to prevent health contributor injection 
    var exclusions = new[] { SteeltoeAssemblies.Steeltoe_Connector_ConnectorCore };

    return builder
        .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
        .AddSteeltoe(exclusions);
}
```

## Environment (please complete the following information):
 - Steeltoe Version 3.2.3
 - Platform: Kubernetes
 - OS: Linux
 - .NET 6

**Comment by TimHess** [comment]
Hi @davgia,

Thanks for filing the bug, it seems like there's room for interpretation on how this should work.

Can you elaborate a bit on when you would want Connectors, Endpoints, Autoconfiguration and have a `SqlClient` reference but not want the Sql Connector automatically wired up?

**Comment by davgia** [comment]
Hi @TimHess,

for me Connector and Endpoint (health check) should be wired up only if the configuration actually contains properties related to the specific Connector. Basically for me there should be no default working values. The default should be `null` and not `localhost:1433`. Of course that depends on the use case. Mine is docker and kubernetes, so localhost is always wrong. That is, of course, not true for other use cases.

**Comment by bart-vmware** [comment]
Hi @davgia,

I've created a sample to reproduce this and debugged into the 3.x sources to find the root cause. The way Steeltoe works is that health checks are *always* wired up, unless the Microsoft built-in health checks are active (see [here](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Connectors/src/ConnectorCore/SqlServerProviderServiceCollectionExtensions.cs#L84), and tests [here](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Connectors/test/ConnectorCore.Test/SqlServerProviderServiceCollectionExtensionsTest.cs#L176)). The name of the boolean `addSteeltoeHealthChecks` parameter is a bit misleading, because it means to _force_ adding Steeltoe health checks _even if the Microsoft health checks are active_. There is currently no way to disable health checks (except for your workaround). Changing this in 3.x is risky, as it will likely break existing users.

I agree that Steeltoe should not "make up" defaults for connection parameters that aren't configured, so I'm changing that in v4.x. Only what's configured will be passed to the underlying driver. However, some drivers (RabbitMQ, for example) use their own defaults and work out of the box without any connection string. Therefore we can't determine whether wire-up should occur based on whether configuration exists.

The way to control whether Steeltoe health checks are wired up in v4 is changing as well. The default value for `options.EnableHealthChecks` will depend on whether the Microsoft built-in health checks are active, but we'll take an `Action<TOptions>` that enables to explicitly turn them on or off.
