### ISSUE TITLE
Add eureka metadata dynamically

### ISSUE THREAD

**Issue by dmarthaler** [SteeltoeOSS/Steeltoe#121]
Question:
How can I dynamically add metadata, so that the EurekaDiscoveryClient in my application will send it to Eureka?

I know that statically configuring it in appsettings.json does work, but I need to be able to add information in a dynamic way. I tried to use ApplicationInfoManager instance, but this instance does not appear to be initialised.

I found a similar question on spring-cloud Github issues: https://github.com/spring-cloud/spring-cloud-netflix/issues/62#issuecomment-62534871

Is there a similar way to do that using dotnet?

**Comment by TimHess** [comment]
It is possible to access the `EurekaApplicationInfoManager` from the DI container, and add metadata to the app instance programmatically... 

```csharp
public MyClass(EurekaApplicationInfoManager infoManager)
{
    _infoManager.InstanceConfig.MetadataMap["some key"] = "Some new value";
}
```

Unfortunately it doesn't look like we have anything wired up to automatically update the registration, but you can call Initialize again with the updated instance config and that seems to work on the next heartbeat:
```csharp
_infoManager.Initialize(_infoManager.InstanceConfig);
```

This use case should be thought about during #131 in case there's a convenient crossover opportunity, otherwise it would be nice if there was a community contribution here
