### ISSUE TITLE
A number of packages are reporting with vulnerabilities/depreciated

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1238]
## Describe the bug
A number of projects including test projects are reporting vulnerabilities some of which are classified as critcal and as such should be addressed

## Steps to reproduce 

1. Open project in visual studio
2. Observe packages in nuget package explorer

## Expected behavior
No warning's for depreciation/vulnerabilities with dependencies updated to the lowest version which removes warning

## Environment (please complete the following information):
 - Steeltoe Version 3.2.6

## Additional context or links

- https://github.com/advisories/GHSA-q7cg-43mg-qp69
- https://github.com/advisories/GHSA-7j9m-j397-g4wx
- https://github.com/open-telemetry/opentelemetry-dotnet/issues/3629

Still to be addressed
- https://github.com/advisories/GHSA-5crp-9r3c-p9vr which will be handled via #1239

**Comment by TimHess** [comment]
Hi @thompson-tomo,

While it would be nice to guarantee that all of our dependencies are free from CVE exposure, the Steeltoe project generally operates by defining a minimum compatible version of dependencies and defers primary responsibility for managing specific references to consuming applications. This practice is not only due to the size of the burden of keeping so many references current, but also due to the potential for unintended consequences. For example, the Newtonsoft issue can only be resolved by forcing a major version bump or ensuring `MaxDepth` is set correctly, without interfering with applications using Steeltoe.

Steeltoe will continue to review and update dependencies during our own major version updates at a minimum, and at other intervals as needed. It is recommended that applications using Steeltoe (and these other dependencies) include these version overrides directly. We are willing to help resolve any compatibility issues that may occur within Steeltoe's realm of control.

Any security concerns discovered within this project should be addressed via the [Steeltoe security policy](https://github.com/SteeltoeOSS/Steeltoe/security/policy)

Warnings aside, the OpenTelemetry issue does read like it might warrant a bump - have you experienced the crash issues mentioned?

**Comment by thompson-tomo** [comment]
Hi @TimHess 

I can fully understand not keeping dependencies upto date especially as some libraries frequently release updates on wanting maximum compatibility etc. That is part of the reason why in the PR I have only bumped the minor/patch versions and only taken it up to the min version required to address the CVE's. For the OTEL I have only bumped the min supported version  but retained the max version so wouldn't anticipate any issues.

**Comment by TimHess** [comment]
In addition to the comment on the now-closed PR, I'll add that we will revisit this topic if these packages become a significant issue that can't be worked around in applications, if we need to add .NET 8 compatibility to this release line, or if a 3.3 release is required for any other reason.

I don't think I stated it in the PR, but one of the other concerns with even bumping to the latest patch is that these are dependencies that we don't directly control and typically don't follow closely enough to know how well they adhere to SemVer. We've been burned in the past with unexpected bugs being introduced just by bumping patch versions, and we think our effort is best spent on Steeltoe 4.0 and all the work around adding a new major release
