### ISSUE TITLE
DataProtection Redis only supports 2.2 of ASP.NET Core

### ISSUE THREAD

**Issue by dtillman** [SteeltoeOSS/steeltoe#125]
## Is your feature request related to a problem? Please describe.
DataProtection Redis only works with 2.2.

## Describe the solution you'd like
Make it work with 2.1 if possible

## Describe alternatives you've considered
None

## Additional context
None

**Comment by TimHess** [comment]
This problem _can_ happen during a nuget restore:
```
NU1107: Version conflict detected for Microsoft.AspNetCore.Cryptography.Internal. Install/reference Microsoft.AspNetCore.Cryptography.Internal 2.2.0 directly to project <projectName> to resolve this issue.
```

This combination results in the above failure:
```
<TargetFramework>netcoreapp2.1</TargetFramework>
<PackageReference Include="Microsoft.AspNetCore.App" />
<PackageReference Include="Steeltoe.Security.DataProtection.RedisCore" Version="2.3.0" />
```
This combination does not:
```
<TargetFramework>netcoreapp2.1</TargetFramework>
<PackageReference Include="Microsoft.AspNetCore" Version="2.1.7" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.3" />
<PackageReference Include="Steeltoe.Security.DataProtection.RedisCore" Version="2.3.0" />
```

This issue is a direct result of changing the dependency in Steeltoe.Security.DataProtection.RedisCore from Microsoft.AspNetCore.DataProtection.Redis (v0.3) to Microsoft.AspNetCore.DataProtection.StackExchangeRedis (v2.2) -- this change was made as what was seen at the time as the simplest way to take advantage of all the improvements in the StackExchange.Redis 2.0 release.

Two potential changes we could make to allow everything to work would be:
1. Multi-targeting `Steeltoe.Security.DataProtection.RedisCore`
1. Releasing multiple packages to align with what MSFT did with the underlying DataProtection packages

Neither of those changes is clean (likely breaking some apps either way), given that we've already shipped changes in this area. Additionally, the Redis DataProtection package for versions < 2.2.0 has been unlisted from nuget.org, underscoring the reasoning for rolling forward to take advantage of the newer v2 StackExchange.Redis driver. I'm inclined to leave this as a known issue (with the workaround of specifying more packages than AspNetCore.App) until/unless further issues are discovered
