### ISSUE TITLE
Update OpenTelemetry.Exporter.OpenTelemetryProtocol constraint

### ISSUE THREAD

**Issue by davgia** [SteeltoeOSS/Steeltoe#1268]
## Is your feature request related to a problem? Please describe.
I'm upgrading to .net 8 and the `OpenTelemetry.Exporter.OpenTelemetryProtocol` constraint (1.3.2) of Steeltoe 3.2.6 make me to manually import `System.Diagnostics.DiagnosticSource` to 8.0.0. This gives me the following warning:

> NU1608 Detected package version outside of dependency constraint: OpenTelemetry.Api 1.3.2 requires System.Diagnostics.DiagnosticSource (>= 6.0.0 && < 8.0.0) but version System.Diagnostics.DiagnosticSource 8.0.0 was resolved.

## Describe the solution you'd like
I would like Steeltoe to allow the latest version of OpenTelemetryProtocol keep in mind this [issue](https://github.com/SteeltoeOSS/Steeltoe/issues/1125).

## Describe alternatives you've considered
Accept the warning (don't know if it can cause problems).

**Comment by TimHess** [comment]
I am not optimistic that we can resolve this issue in the 3.x line due to significant breaking changes in the OpenTelemetry APIs and the combination of target frameworks between OpenTelemetry and Steeltoe (and certainly not without breaking SemVer expectations with Steeltoe releases.

The best path forward is going to be Steeltoe v4. The [first public milestone release](https://github.com/SteeltoeOSS/Steeltoe/milestone/28) should ship to nuget.org sometime this summer.
