### ISSUE TITLE
[QUESTION] Using Microsoft.Extensions.Logging with Config Server

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1285]
## Question
How can i pass my logger which is of Microsoft.Extensions.Logging into AddConfigServer so that the logs from the config server configuration provider is in a consistent manner with the rest of my logs.

## Environment (please complete the following information):
 - .NET 8
 - Steeltoe Version 3.2.6

**Comment by TimHess** [comment]
Due to the way Configuration providers integrate with the any of the hosts Microsoft offers, you have to build a separate `ILoggerFactory` for use before the shared one is available. There are a couple of ways to do this here:

- [As we have documented](https://docs.steeltoe.io/api/v3/configuration/config-server-provider.html#enable-logging), (build a separate, custom LoggerFactory just for startup)
   - There is an `IHostedService` that is automatically added from the [HostBuilder extensions](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Configuration/src/ConfigServerCore/ConfigServerHostBuilderExtensions.cs), or can be added with [`AddConfigServerServices()`](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Configuration/src/ConfigServerBase/ConfigServerServiceCollectionExtensions.cs#L79) which will replace this startup LoggerFactory with your common logging configuration once it is available
- Use [BootstrapLoggerFactory.Instance](https://github.com/SteeltoeOSS/Steeltoe/tree/release/3.2/src/Common/src/Common/Logging), optionally adding the [`BootstrapLoggerHostedService`](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Common/src/Common.Hosting/BootstrapLoggerHostedService.cs) so that your common logging configuration can be applied once it is available

**Comment by thompson-tomo** [comment]
Thanks @TimHess  that has been super helpful, i has missed the logger factory option.
