### ISSUE TITLE
Schemas for Eureka should be extracted & become public

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1289]
## Is your feature request related to a problem? Please describe.
I want to be able to implement my own Eureka endpoint for registering my micro services

## Describe the solution you'd like

- All files starting with JSON in the Steeltoe.Discovery.Eureka/Transport folder are extracted to standalone package => Steeltoe.Eureka.JSON
- All files remaining in Steeltoe.Discovery.Eureka/appInfo, Steeltoe.Discovery.Eureka/Transport & Steeltoe.Discovery.Eureka/Util are extracted to standalone package => Steeltoe.Eureka with dependency on Steeltoe.Eureka.JSON
- Steeltoe.Discovery.Eureka has a dependency on Steeltoe.Eureka
- All classes appropiate in the JSON now become public

## Describe alternatives you've considered

- Create my own classes
- Ditch the JSON package and simply have the Steeltoe.Eureka package

## Additional context
n/a

**Comment by bart-vmware** [comment]
The Java version of Eureka (both server and client) is provided by Netflix. Spring boot inherits from that and provides a tin layer to work well with the Spring ecosystem. Parts of both were ported to .NET in Steeltoe. Steeltoe provides just the parts needed for service discovery to work well with Spring, CloudFoundry, and Kubernetes. So the .NET port is a limited implementation that isn't intended to support the level of flexibility the Netflix implementation provides. In Steeltoe v4, the code was further cleaned up, because the Steeltoe team currently doesn't intend to maintain a full Eureka client library. During public API review for Steeltoe v4, several interfaces were removed and types were made internal to clarify the expected extensibility points and to reduce maintenance by making it easier to refactor internals without affecting users.

Opening up things more, as proposed here, goes against that philosophy. The thing is that most of Eureka is poorly documented and it's pretty hard to get things right. We've had to do a lot of exploration and experimentation to get to what we have now, intentionally avoiding several topics that we don't need for service discovery. Perhaps, some day, Steeltoe or another project may provide a fully featured Eureka client, but that's not something we're looking at for now.
