### ISSUE TITLE
Mappings endpoint should return parameters for url

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1307]
## Is your feature request related to a problem? Please describe.
The mappings endpoint can make available a list of parameters required however the Steeltoe Implementation doesn't attempt to process them.

## Describe the solution you'd like
When the mappings actuator/endpoint is called, the user should be informed if the url supports parameters required for URL.

## Additional context
Implementation is clear that it is not implemented yet: https://github.com/SteeltoeOSS/Steeltoe/blob/15a935310989d02eba940116cc5f911a3bd96f78/src/Management/src/Endpoint/RouteMappings/RouteMappingDescription.cs#L93
Parameters can be obtained from: Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor.Parameters

**Comment by bart-vmware** [comment]
This was a deliberate choice in https://github.com/SteeltoeOSS/Steeltoe/pull/1153. I don't exactly remember _why_ this information was hard to obtain, but I suspect we could only support the simple cases (attribute-based routing, no constraints, no patterns, method parameter name equals route parameter name, etc) and be wrong otherwise.
