### ISSUE TITLE
Add Kafka connector

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#132]
Add support for the Kafka connector

**Comment by cesinhaugusto** [comment]
Guys, I'd like to do this one. I believe this would be similar to the RabbitMQ implementation, right?

**Comment by TimHess** [comment]
I initially thought this would be similar to what we have for RabbitMQ, but a large part of the reason we have connectors is to make it easier to consume the bindings provided by Cloud Foundry - but as far as I could tell, there is no broker for Kafka, so it's a lot less clear what this idea of a Kafka connector actually looks like... As such, I was expecting we would be revisiting this issue in the context of Streams (#128), after the first round of that work is merged in

**Comment by cesinhaugusto** [comment]
Great to hear. This will need further discussion then. I'll research more about Spring Streams in the meantime. Instead of tackling this one, I'll start on commenting public interfaces, as you've suggested before, to get more familiar with the project. Hopefully, I'll be able to contribute on Streams then.

**Comment by csterwa** [comment]
Due to the scope of capabilities needed to deliver Steeltoe Messaging support for RabbitMQ, which is the initial Messaging implementation, Steeltoe OSS team is going to focus on delivering it first before tackling another messaging platform such as Kafka. We will update this issue when we have a better idea of which release that Kafka support will be addressed. Please let us know if there are any questions or concerns. Thank you.
