### ISSUE TITLE
BootstrapLoggerHostedService not resulting in replaced loggers

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Steeltoe#1338]
## Is your feature request related to a problem? Please describe.

Maybe I'm just missing something, but when I do this:
```
builder.AddConfigServer(BootstrapLoggerFactory.Default);
```
The loggerfactory appears to never get replaced

## Describe the solution you'd like
Have a way to register the internal type `BootstrapLoggerHostedService`

**Comment by bart-vmware** [comment]
It depends on what `builder` is. If it's `IConfigurationBuilder`, then this is by design. Call the extension method from a host builder extension, such as `WebApplicationBuilder`, to set up the replacement.

**Comment by TimHess** [comment]
This encounter started with `WebApplicationBuilder`, so my initial assessment of what was happening is somewhat incorrect...

The `WebApplicationBuilder` extension does indeed register the necessary hosted service - might there be other scenarios, such as using the `IConfigurationBuilder` extension, for which where there should be a public method to register `BootstrapLoggerHostedService`?

I'm still digging on what is wrong with bootstrap logger replacement at startup - I have discovered that the `_loggersByCategoryName` dictionary is populated as the config providers are built and loggers are created, but empty when the Hosted Service starts

**Comment by TimHess** [comment]
Well... `_loggersByCategoryName` is empty because `BootstrapLoggerHostedService` calls `.Update` on a _new_ BootstrapLoggerFactory instead of `BootstrapLoggerFactory.Default` -- I think this broke in #1243.

1. Here's how we initially get the factory:
   - `BootstrapLoggerFactory.Default { get; } = new UpgradableBootstrapLoggerFactory()` 
1. Here's how the "replacement" happens:
   - `BootstrapLoggerHostedService.StartAsync()` calls 
   - `_context.GetBootstrapLoggerFactory()` returns 
   - `BootstrapLoggerFactory.GetInstance(_key)`, where `_key` == the `HostBuilderWrapper`
   - `return InstanceMap.GetOrAdd(contextKey, _ => new UpgradableBootstrapLoggerFactory());`

So, I think we need to use a key to identify the loggerfactory either always or never... I think never would be better since there is supposed to only be one logger factory, and that's what we'll end up with after the replacement completes

**Comment by bart-vmware** [comment]
Thanks for the analysis, I understand what's happening now.

We do need support for multiple instances, so that tests running in parallel won't influence each other. This is why I introduced `BootstrapLoggerContext`. I think the best course of action is to remove the static `BootstrapLoggerFactory.Default` and replace it with `BootstrapLoggerFactory.Create()`, which would always return a new instance. This enables consumers to pass it around freely, reusing it (in app) or not (in tests).

**Comment by bart-vmware** [comment]
Related: Remove activating the bootstrap logger hosted service from host builder extension methods in `Steeltoe.Configuration`. A public API should be provided to do that, so that configuration providers don't carry that responsibility. Then the host builder extension methods in `Configuration.Encryption` can be removed.
