### ISSUE TITLE
WindowsNetworkFileShare nuget version 2.4.0 throw Bad Name

### ISSUE THREAD

**Issue by pnguyen535** [SteeltoeOSS/steeltoe#202]
Hello,

for some reason, the code below work in version 2.2.0, but failed in 2.4.0

 using (WindowsNetworkFileShare networkPath = new WindowsNetworkFileShare(sharePath, ShareCredentials))
            {
                return new ActionResult<IEnumerable<string>>(new List<string>());
            }

Thank you

**Comment by TimHess** [comment]
Hello @pnguyen535,

Are you sure nothing else has changed for you? There were _very_ few changes to that code in that time. I believe the Bad Net Name message is coming from the operating system and is just relayed by Steeltoe. As I understand it, that message happens when you pass in a local path (eg: `z:/share/file.txt`) instead of a UNC path (eg: `//server/share/file.txt`)

**Comment by TimHess** [comment]
https://github.com/SteeltoeOSS/Samples/issues/127

**Comment by pnguyen535** [comment]
Hi Tim, 
I know the error message is from OS, but I could not get the code to run under 2.4.0 version. However, it works when I switched to 2.2.0. I tested multiple times.

Thanks

**Comment by TimHess** [comment]
Sure enough, there's a definitely a bug here. I'll look at it first thing tomorrow
