### ISSUE TITLE
Add Kafka binder to the streams code

### ISSUE THREAD

**Issue by dtillman** [SteeltoeOSS/Steeltoe#242]

**Comment by TimHess** [comment]
The core team is not likely to work on this prior to Steeltoe 4.0, if it is important to you and you would like to help build it, please reach out and we'd be happy to help you get it done

**Comment by csterwa** [comment]
Due to the scope of capabilities needed to deliver Steeltoe Messaging support for RabbitMQ, which is the initial Messaging implementation, Steeltoe OSS team is going to focus on delivering it first before tackling another messaging platform such as Kafka. We will update this issue when we have a better idea of which release that Kafka support will be addressed. Please let us know if there are any questions or concerns. Thank you.
