### ISSUE TITLE
Kafka support for Streams and Data Flow

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Steeltoe#300]
Add Kafka to our supported Streams implementations

**Comment by csterwa** [comment]
Due to the scope of capabilities needed to deliver Steeltoe Messaging support for RabbitMQ, which is the initial Messaging implementation, Steeltoe OSS team is going to focus on delivering it first before tackling another messaging platform such as Kafka. We will update this issue when we have a better idea of which release that Kafka support will be addressed. Please let us know if there are any questions or concerns. Thank you.
