### ISSUE TITLE
What does the 'healthCheckPath' actually mean in consul discovery

### ISSUE THREAD

**Issue by zh6335901** [SteeltoeOSS/Steeltoe#309]
I am testing out the Consul Discovery. And i see the document said the `consul:discovery:healthCheckPath` setting is server health check path, we can set the setting to provide our own health check. So i set this setting in my sample project:
```
  "Consul": {
    "Host": "localhost",
    "Port": 8500,
    "Discovery": {
      "ServiceName": "Test",
      "HealthCheckPath": "/health",
      "Port": 5000
    }
  }
```
And in my sample project startup, I config the health check endpoint by `Microsoft.Extensions.Diagnostics.HealthChecks` packages:
```
services.AddHealthChecks()
    .AddCheck("self", () => HealthCheckResult.Healthy());

....

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapHealthChecks("/health");
});
```

But when i started the project, I can't see the consul detect the `/health` endpoint. Even i change the health check result to unhealthy, The service check in consul still be passed. So i'm confused the setting,  And want to know how to config the health check for consul discovery  use

**Comment by hananiel** [comment]
HealthCheckPath means the stem of the url off the HostName (defaults to machine name) so running locally on windows machine the healthcheckUrl becomes   http://desktop-1jnk1hq:5000/health. So your assumption is correct.

The reason the configuration wasnt working as expected was because by default Consul Configuration is using TTL controlled by "consul:Discovery:Heartbeat:Enabled" which is true. 
In order to use actuator or Msft Health checks, you need something like this.  

```
"consul": {
    "Host": "localhost",
    "Port": 8500,
    "Discovery": {
      "Heartbeat": {
        "Enabled": "false"
      },
      "HostName": "host.docker.internal", 
      "ServiceName": "Test1235",
      "HealthCheckPath": "/health",
      "Port": 5000
    }
  }
```
In addition it helps in the consul ui to see the healthcheck type being used ex. TTL or HTTP. You want it to be HTTP and the note below has helpful error messages while trying to reach the health check endpoint. 
![consul](https://user-images.githubusercontent.com/887691/80826484-541e5380-8bb0-11ea-9e0e-8d5ee7812e06.png)

Let me know if you have any more questions.

**Comment by zh6335901** [comment]
@hananiel Thanks! It's worked

**Comment by asalhani** [comment]
@hananiel  Thank for the great clearification. It worked based in your suggestion..
