### ISSUE TITLE
using RoundRobinLoadBalancer with redis

### ISSUE THREAD

**Issue by dboy2018** [SteeltoeOSS/Steeltoe#368]
## Describe the bug
There are some instances in the Eureka.When I remove or add a instance,ServiceInstances-XXXX can't update.
So I add DistributedCacheEntryOptions into the file.

IServiceInstanceProviderExtensions.cs
      if (distributedCache != null)
            {
                await distributedCache.SetAsync(serviceInstancesKeyPrefix + serviceId, SerializeForCache(MapToSerializable(instances)),**new DistributedCacheEntryOptions()
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(10)
                }**).ConfigureAwait(false);
            }

Is it OK?

## Environment (please complete the following information):
 - Steeltoe 2.4.4

**Comment by dboy2018** [comment]
RandomLoadBalancer is the same

**Comment by TimHess** [comment]
You're right, it looks like we are completely missing the ability to set the expiration on cache entries with the load balancers, which is a feature that would be expected to be present and it's fair to call that a bug...

This is a feature we need, but it should be configurable rather than hard-coded, so we'll also need to add a mechanism for either reading app configuration or accepting `DistributedCacheEntryOptions` in the constructor.

This is an item that would be a good first issue for anyone wishing to contribute a bit of code, but it is also important enough that I'll pick it up and make sure it is in the next release if no one else does.

Should you need an immediate solution, you can always inherit either of those load balancers and override the relevant method
