### ISSUE TITLE
Error	BC30560	'OpenIdConnectOptions' is ambiguous in the namespace 'Steeltoe.Security.Authentication.CloudFoundry.Owin'.

### ISSUE THREAD

**Issue by ajdepoti** [SteeltoeOSS/steeltoe#38]
###Title
VB.NET compile error:  'OpenIdConnectOptions' is ambiguous in the namespace 'Steeltoe.Security.Authentication.CloudFoundry.Owin'.

### Issue 
Error	BC30560	'OpenIdConnectOptions' is ambiguous in the namespace 'Steeltoe.Security.Authentication.CloudFoundry.Owin'.

### Expected Result
solution would compile successfully

### Actual Result
Build fails with the above error message

### Steps to Repro
Create a VB.Net project.  add the Startup.vb contents

```
Imports Microsoft.Owin
Imports Microsoft.Owin.Security
Imports Microsoft.Owin.Security.Cookies
Imports Owin
Imports Steeltoe.CloudFoundry.Connector
Imports Steeltoe.CloudFoundry.Connector.Services
Imports Steeltoe.Security.Authentication.CloudFoundry.Owin



<Assembly: OwinStartup(GetType(yournamespace.Startup))>
Namespace yournamespace
    Public Class Startup
        Public Sub Configuration(ByVal app As IAppBuilder)
            app.Use(Function(context, [next])
                        context.Request.Scheme = "https"
                        Return [next]()
                    End Function)

            app.SetDefaultSignInAsAuthenticationType("ExternalCookie")
            app.UseCookieAuthentication(New CookieAuthenticationOptions With {
                .AuthenticationType = "ExternalCookie",
                .AuthenticationMode = AuthenticationMode.Active,
                .CookieName = ".AspNet.ExternalCookie",
                .ExpireTimeSpan = TimeSpan.FromMinutes(5)
            })

            Dim serviceInfos = CloudFoundryServiceInfoCreator.Instance(ApplicationConfig.Configuration)
            Dim ssoInfo = serviceInfos.GetServiceInfos(Of SsoServiceInfo)().FirstOrDefault()

            If ssoInfo Is Nothing Then
                Throw New NullReferenceException("Service Info Not Found")
            End If

            app.UseOpenIDConnect(New OpenIdConnectOptions() With {
                .ClientID = ssoInfo.ClientId,
                .ClientSecret = ssoInfo.ClientSecret,
                .AuthDomain = ssoInfo.AuthDomain,
                .AppHost = ssoInfo.ApplicationInfo.ApplicationUris.First(),
                .AppPort = 0,
                .ValidateCertificates = False
            })
        End Sub
    End Class
End Namespace

```

### Further Details
n/a

**Comment by TimHess** [comment]
Can you use the newer `app.UseCloudFoundryOpenIdConnect(ApplicationConfig.Configuration)` as in this sample? https://github.com/SteeltoeOSS/Samples/blob/dev/Security/src/AspDotNet4/CloudFoundrySingleSignon-VB/App_Start/Security.vb

It should resolve your issue, prevent the need for directly retrieving the service info and it takes real request path into account at runtime instead of trying to hardcode the app's uri information from a service binding.

**Comment by pnguyen535** [comment]
Hi Tim,

I am using asp.net core, I ran into the issue with ClaimsTransformation as described in the link below. Is there a way to open up the OpenIdConnectOptions oidcOptions

Thank you

https://stackoverflow.com/questions/47929027/getting-access-token-within-claims-transformer-in-asp-net-core

**Comment by TimHess** [comment]
Hi @pnguyen535,

This issue is specific to using a Steeltoe package that adds OWIN functionality to a VB app. This package should not be used in ASP.NET Core, and your issue should not be related this issue. Please open a separate issue for providing access to `CloudFoundryOpenIdConnectOptions`

**Comment by pnguyen535** [comment]
Ok, I will open a separate issue 
Thank you 


Sent from Yahoo Mail for iPhone


On Friday, August 9, 2019, 7:55 AM, Tim Hess <notifications@github.com> wrote:


Hi @pnguyen535,

This issue is specific to using a Steeltoe package that adds OWIN functionality to a VB app. This package should not be used in ASP.NET Core, and your issue should not be related this issue. Please open a separate issue for providing access to CloudFoundryOpenIdConnectOptions

**Comment by TimHess** [comment]
Between the available workaround and the removal of the obsolete classes (will be in the next release of 2.3.0), I'm feeling like its appropriate to close this issue. Please re-open this issue if you need further assistance
