### ISSUE TITLE
Project targeting .NET 5 and Steeltoe 3.0.1 packages not working with PublishSingleFile=true

### ISSUE THREAD

**Issue by antonpopov** [SteeltoeOSS/Steeltoe#520]
## 
Since upgrading to .NET 5.0 when the project (which is using **Steeltoe.Discovery.Eureka 3.0.1** and **Steeltoe.Extensions.Configuration.ConfigServerCore 3.0.1**) is deployed to Red Hat Enterprise **Linux** Server or **Windows** Server the application is **not working**. Local everything is working as expected. The problem occurs when the application is deployed. Though, there is no problem when having installed Steeltoe packages in version 2.4.1 for example, in a project targeting .NET 5.

## Steps to reproduce 
1. Create new ASP.NET Core Web Api project with targeting framework .NET 5.
2. Install Steeltoe.Extensions.Configuration.ConfigServerCore 3.0.1 and configure the project to work with an instance of a config server.
3. Publish the application using:
dotnet publish -r win-x64 --no-self-contained -o "D:\Test" -c Release  /p:PublishSingleFile=true
4. Start the application - an exception is thrown.

## Environment:
 - Steeltoe Version [3.0.1]
 - OS: [Linux - RHEL 7.6, Windows Server]
 - .NET Version [.NET 5] 

## Screenshots
![image](https://user-images.githubusercontent.com/5244097/99798031-f09e4800-2b38-11eb-9016-2c4e7e89bfc0.png)

**Comment by TimHess** [comment]
To be clear, this application works when the Target Framework is netcoreapp3.1, and changing only that results in this exception?

**Comment by antonpopov** [comment]
That's correct.

**Comment by TimHess** [comment]
The only thing that would make sense here is if the problem is this line:
```
public static string SteeltoeUserAgent { get; } = 
                $"Steeltoe/{FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion}";
```
It looks like it's failing to get the location of the executing assembly. I haven't seen or heard of any breaking changes in this area, but Microsoft has a different recommendation for getting the path of an assembly anyway, So I did a custom build of Steeltoe.Common.Http that changes that line to look like this:
```
public static string SteeltoeUserAgent { get; } = 
                $"Steeltoe/{FileVersionInfo.GetVersionInfo(typeof(HttpClientHelper).Assembly.Location).FileVersion}";
```
Could you try it out by adding a reference to `Steeltoe.Common.Http` version `3.0.2-useragent` from the [dev feed](https://www.myget.org/F/steeltoedev/api/v3/index.json)?

**Comment by antonpopov** [comment]
I added a reference to `Steeltoe.Common.Http` version `3.0.2-useragent` but with no success. Still the same exception is thrown.

![image](https://user-images.githubusercontent.com/5244097/99835323-1e9d7f80-2b6d-11eb-8427-8250f6b436ee.png)

**Comment by TimHess** [comment]
Alright, do you still have the issue if you publish without `/p:PublishSingleFile=true` ?

**Comment by antonpopov** [comment]
I can confirm that this "fixed" the problem. I also removed the reference to `Steeltoe.Common.Http` version `3.0.2-useragent` and there is no issue without having `/p:PublishSingleFile=true`.

**Comment by TimHess** [comment]
Well, at least it is clearer why it's failing now! I've pushed a new version of `3.0.2-useragent-2`, do you think you could give that a try with `PublishSingleFile=true`?

The affected code now looks like this `$"Steeltoe/{typeof(HttpClientHelper).Assembly.GetName().Version}"`

**Comment by TimHess** [comment]
Same basic story... This one is probably going to be harder to solve though because it needs to find types in other assemblies, and [the current approach](https://github.com/SteeltoeOSS/Steeltoe/blob/master/src/Common/src/Common/Reflection/ReflectionHelpers.cs#L294) does actually depend on looking at other files in the same directory.

I've got to fix a couple issues with our integration tests today and I'm off work next week, so I'm not sure I'll be able to get to this right away. If this is urgent for you, a PR would be welcomed

**Comment by antonpopov** [comment]
Thank you. If I have enough time, I'll investigate on the issue.

**Comment by jkonicki** [comment]
Tying this issue to PR #536 

Created follow-up issue to address the remaining areas:  #544
