### ISSUE TITLE
WindowsNetworkFileShare: Error 1219

### ISSUE THREAD

**Issue by manali1st** [SteeltoeOSS/Steeltoe#603]
When Try to connect same shared drive to perform parallel download on multiple files, I get error 1219 and description is unknown. 
If download both files in sequential, it doesn't give any error.
I am using File.Open to read bytes after connect.
 
There should not be limitation of parallel download on same network drive.

```
using (WindowsNetworkFileShare nt = new WindowsNetworkFileShare("\\storagepath", _shareCredential))
            {

                using (FileStream stream = File.OpenRead(fullpath))
                {
```

**Comment by TimHess** [comment]
Could you provide a minimal console app that demonstrates the problem?

From memory, I think that if you try to create the same `WindowsNetworkFileShare` multiple times that's the same as requesting the same drive mapping multiple times, which is problematic for the OS. You might have to change how you open that connection so that the fileshare connection can be shared

**Comment by TimHess** [comment]
Please provide a more complete sample of the problem if you're still experiencing an issue
