### ISSUE TITLE
PlaceholderResolver does not respect updates to configuration sources

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#830]
With the latest version of .NET6 runtime (6.0.201) it appears there is change to the implementation of  IConfiguration. Previously on this [line  ](https://github.com/SteeltoeOSS/Steeltoe/blob/8e9686587844f86b40135cbe73d6d193f0c4bcb5/src/Configuration/src/PlaceholderBase/PlaceholderResolverProvider.cs#L80) it would return the actual placeholder value which would be resolved from the current sources. 

But with the latest version it appears to be cached - so the previous value is returned instead of what it should after any changes to configuration sources. 

Makes this test fail: https://github.com/SteeltoeOSS/Steeltoe/blob/8e9686587844f86b40135cbe73d6d193f0c4bcb5/src/Configuration/test/PlaceholderBase.Test/PlaceholderResolverProviderTest.cs#L288

**Comment by bart-vmware** [comment]
The reason for the test failure is that when removing a source from `ConfigurationManager`, it [rebuilds the entire configuration](https://github.com/dotnet/runtime/blob/4cdbfdcca352e0f12e4829eb3fec638d717add51/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationManager.cs#L135-L157). This doesn't happen when changing the sources inside the placeholder, because  `ConfigurationManager` is unaware of the change. Here are some ways to force a rebuild:
1. Call `((IConfigurationBuilder)builder.Configuration).Sources.Remove(null!)`
2. Call `((IConfigurationBuilder)builder.Configuration).Properties.Remove(string.Empty)`
