### ISSUE TITLE
Update dependencies to resolve Grype CVEs

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#890]
## Is your feature request related to a problem? Please describe.
A number of steeltoe dependencies need updated to latest versions to resolve CVEs as reported by Grype

| Name | Installed | Fixed | Type | Vulnerability | Severity |
| ------------- | ------------- |------------- | ------------- |------------- | ------------- |
| Google.Protobuf | 3.11.4 | 3.15.0 | dotnet | GHSA-77rm-9x9h-xj3g | High |
| Microsoft.AspNetCore.Authentication.JwtBearer | 3.1.0 | 3.1.18 | dotnet | GHSA-q7cg-43mg-qp69 | Medium|
Microsoft.AspNetCore.Authentication.JwtBearer | 5.0.0 | 5.0.9 | dotnet | GHSA-q7cg-43mg-qp69 | Medium
Microsoft.AspNetCore.Authentication.JwtBearer | 2.1.0 | 2.1.29 | dotnet | GHSA-q7cg-43mg-qp69 | Medium
Microsoft.AspNetCore.Http | 2.1.0 | 2.1.22 | dotnet | GHSA-hxrm-9w7p-39cc | High
Microsoft.AspNetCore.Server.Kestrel.Core | 2.1.0 | 2.1.7 | dotnet | GHSA-6px8-22w5-w334 | High
Microsoft.AspNetCore.Server.Kestrel.Core | 2.1.0 | 2.1.2 | dotnet | GHSA-cgpw-2gph-2r9g | Medium
Microsoft.NETCore.App | 2.1.0 | 2.1.7 | dotnet | GHSA-5633-f33j-c6f7 | Medium
Microsoft.NETCore.App | 2.1.0 | 2.1.7 | dotnet | GHSA-6px8-22w5-w334 | High
Microsoft.NETCore.App | 2.1.0 | 2.1.8 | dotnet | GHSA-x5qj-9vmx-7g6g | Medium
Newtonsoft.Json | 9.0.1 | 13.0.1 | dotnet | GHSA-5crp-9r3c-p9vr | High
Newtonsoft.Json | 10.0.1 | 13.0.1 | dotnet | GHSA-5crp-9r3c-p9vr | High
Newtonsoft.Json | 11.0.2 | 13.0.1 | dotnet | GHSA-5crp-9r3c-p9vr | High
Newtonsoft.Json | 10.0.2 | 13.0.1 | dotnet | GHSA-5crp-9r3c-p9vr | High
Newtonsoft.Json | 12.0.2 | 13.0.1 | dotnet | GHSA-5crp-9r3c-p9vr | High
Newtonsoft.Json | 10.0.3 | 13.0.1 | dotnet | GHSA-5crp-9r3c-p9vr | High
Newtonsoft.Json | 12.0.3 | 13.0.1 | dotnet | GHSA-5crp-9r3c-p9vr | High
SSH.NET | 2020.0.0-beta1 | 2020.0.2 | dotnet | GHSA-72p8-v4hg-v45p | Medium
System.DirectoryServices.Protocols | 4.7.0 | 5.0.1 | dotnet | GHSA-9cxh-gqpx-qc5m | Medium
System.IO.Pipelines | 4.5.0 | 4.5.1 | dotnet | GHSA-j378-6mmw-hqfr | High
System.Net.Http | 4.3.0 | 4.3.4 | dotnet | GHSA-7jgj-8wvc-jh57 | High
System.Net.Http.WinHttpHandler | 4.0.0 | 4.0.1 | dotnet | GHSA-qhqf-ghgh-x2m4 | High
System.Net.Http.WinHttpHandler | 4.0.0 | 4.0.1 | dotnet | GHSA-ch6p-4jcm-h8vh | Medium
System.Net.Http.WinHttpHandler | 4.0.0 | 4.0.1 | dotnet | GHSA-j8f4-2w4p-mhjc | Medium
System.Net.Http.WinHttpHandler | 4.0.0 | 4.0.1 | dotnet | GHSA-6xh7-4v2w-36q6 | High
System.Net.Security | 4.3.0 | 4.3.1 | dotnet | GHSA-qhqf-ghgh-x2m4 | High
System.Net.Security | 4.3.0 | 4.3.1 | dotnet | GHSA-6xh7-4v2w-36q6 | High
System.Net.Security | 4.3.0 | 4.3.1 | dotnet | GHSA-j8f4-2w4p-mhjc | Medium
System.Net.Security | 4.3.0 | 4.3.1 | dotnet | GHSA-ch6p-4jcm-h8vh | Medium
System.Private.ServiceModel | 4.5.0 | 4.5.3 | dotnet | GHSA-p9wx-v264-q34p | Medium
System.ServiceModel.Primitives | 4.5.0 | 4.5.3 | dotnet | GHSA-p9wx-v264-q34p | Medium
System.Text.Encodings.Web | 4.6.0 | 4.7.2 | dotnet | GHSA-ghhp-997w-qr28 | Critical
System.Text.Encodings.Web | 4.5.0 | 4.5.1 | dotnet | GHSA-ghhp-997w-qr28 | Critical
System.Text.Encodings.Web | 4.7.0 | 4.7.2 | dotnet | GHSA-ghhp-997w-qr28 | Critical
System.Text.Encodings.Web | 4.4.0 | 4.5.1 | dotnet | GHSA-ghhp-997w-qr28 | Critical
System.Text.Encodings.Web | 4.7.1 | 4.7.2 | dotnet | GHSA-ghhp-997w-qr28 | Critical
System.Text.RegularExpressions | 4.3.0 | 4.3.1 | dotnet | GHSA-cmhx-cq75-c4mj | Medium

**Comment by TimHess** [comment]
For any concerned readers, it is worth noting that any of these dependencies should be updateable at any time by any applications using Steeltoe.

**Comment by TimHess** [comment]
While it would be nice if we could guarantee that all of our dependencies are free from CVEs, the Steeltoe project cannot take on responsibility for managing transitive references (essentially overriding the dependencies specified in packages that are upstream of Steeltoe) not only due to the size of the burden, but also due to the potential for unintended consequences.  For example, there is a CVE on a version of Newtonsoft that can only be resolved by forcing a major version bump. This type of dependency specification makes little sense for us to introduce at a time we're actively moving away from any direct reference to that particular project.

Steeltoe will continue to review and update dependencies during our own major version updates at a minimum, and at other intervals as needed. It is recommended that applications using Steeltoe (and these other dependencies) include these version overrides directly. We are willing to help resolve any compatibility issues that may occur within Steeltoe's realm of control. 

Any security concerns discovered within this project should be addressed via the [Steeltoe security policy](https://github.com/SteeltoeOSS/Steeltoe/security/policy)
